version: '3.8'

services:
  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - neuronest-network

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - FRONTEND_URL=http://frontend:3000
      - MONGODB_URI=mongodb://mongo:27017/neuronest
      - DOCKER_ENABLED=true
      - DOCKER_NETWORK=neuronest-network
      - PROJECTS_DIR=/app/projects
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./projects:/app/projects
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mongo
    networks:
      - neuronest-network

  # MongoDB service
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - neuronest-network

networks:
  neuronest-network:
    driver: bridge

volumes:
  mongo-data: