version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SECRET_KEY=${SECRET_KEY:-supersecretkey}
      - FIREBASE_CREDENTIALS=${FIREBASE_CREDENTIALS}
      - FIREBASE_WEB_API_KEY=${FIREBASE_WEB_API_KEY}
      - DEFAULT_AI_PROVIDER=${DEFAULT_AI_PROVIDER:-gemini}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ENABLE_CODE_EXECUTION=${ENABLE_CODE_EXECUTION:-false}
      - DOCKER_BASE_IMAGE=${DOCKER_BASE_IMAGE:-python:3.10-slim}
      - DOCKER_NETWORK=${DOCKER_NETWORK:-none}
      - DOCKER_TIMEOUT=${DOCKER_TIMEOUT:-30}
      - DOCKER_MEMORY_LIMIT=${DOCKER_MEMORY_LIMIT:-512m}
      - UPLOAD_DIR=${UPLOAD_DIR:-./static/uploads}
      - PROJECTS_DIR=${PROJECTS_DIR:-./static/projects}
      - MAX_UPLOAD_SIZE=${MAX_UPLOAD_SIZE:-10485760}
      - ENABLE_SPEECH_RECOGNITION=${ENABLE_SPEECH_RECOGNITION:-true}
      - SPEECH_RECOGNITION_PROVIDER=${SPEECH_RECOGNITION_PROVIDER:-google}
    restart: unless-stopped